---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 734079328351199232-qE1faJysMNBZY9vPAP38Ed7t3LTGRcM
:access_token_secret: lOf4liMbVohKBm0aUT0MpSj5xO5Sl7xwyjrazn3Q7DnHY
